profile: schooldevops
region: ap-northeast-2
secrets: myproject/schooldevops
environments: 
  - dev
  # - stg
  # - prod
# k8sHost 는 kubectl config view 로 대상 kubernetes 접근 경로를 확인하여 적용한다. 
k8sHost: https://kubernetes.docker.internal:6443
configFilePath: /Users/kido/.kube/config
namespace: default
secretsName: myproject-secrets
secretkeys:  
  DB_URL: username
  DB_USERNAME: username
  DB_PASSWORD: password
  USER_TOKEN: usertoken
configMapsName: myproject-config
configkeys:
  CONNECTION_TIMEOUT: CONNECTION_TIMEOUT
  MAX_CONNECTION: MAX_CONNECTION
  IDLE_CONNECTION: IDLE_CONNECTION  