profile: schooldevops
region: ap-northeast-2
secrets: myproject/schooldevops
environments: 
  - dev
  # - stg
  # - prod
context: docker-desktop
namespace: default
secretsName: myproject-secrets
secretkeys:  
  DB_URL: username
  DB_USERNAME: username
  DB_PASSWORD: password
  USER_TOKEN: usertoken
configMapsName: myproject-config
configkeys:
  CONNECTION_TIMEOUT: CONNECTION_TIMEOUT
  MAX_CONNECTION: MAX_CONNECTION
  IDLE_CONNECTION: IDLE_CONNECTION  