profile: schooldevops
configFilePrefix: application
ext: yml
targetPath: ./
region: ap-northeast-2
secrets: myproject/schooldevops
environments: prod
  # dev
  # stg
  # prod
secretkeys:  
  DB_URL: username
  DB_USERNAME: username
  DB_PASSWORD: password
  USER_TOKEN: usertoken