profile: schooldevops
configFilePrefix: application
ext: yml
targetPath: ./
region: ap-northeast-2
secrets: myproject/schooldevops
environments:
  - dev  
secretkeys:
  DB_USERNAME: username
  DB_PASSWORD: password
  DB_URL: DB_URL