spring: 
  datasource: 
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy 
    url: jdbc:log4jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC 
    hikari: 
      username: ${DB_USERNAME:username} 
      password: ${DB_PASSWORD:1234}
      maximum-pool-size: 10

api:
  user:
    token: ${USER_TOKEN}